traefik:
  deployment:
    kind: DaemonSet
  ports:
    websecure:
      port: 443
      expose: true
      hostPort: 443
      tls:
        enabled: true
  dashboard:
    enabled: true
  providers:
    kubernetesIngress:
      enabled: true
  additionalArguments:
    - "--api.insecure=true"
    - "--serverstransport.insecureskipverify=true"
    - "--entrypoints.websecure.http.tls.certresolver=myresolver"
