traefik:
  deployment:
    kind: DaemonSet
    ports:
    websecure:
      port: 443
      hostPort: 443
      expose:
        default: true
      tls:
        enabled: true
  dashboard:
    enabled: true
  providers:
    kubernetesIngress:
      enabled: true
  additionalArguments:
    - "--api.insecure=true"
    - "--serverstransport.insecureskipverify=true"
