gitlab:
  global:
    hosts:
      domain: gitlab.clementpnn.com
    ingress:
      configureCertmanager: false
      class: traefik
    upgradeCheck:
      enabled: false
  nginx-ingress:
    enabled: false
  gitlab-upgrade-check:
    enabled: false
  shared-secrets:
    enabled: true
  webservice:
    resources:
      requests:
        cpu: "500m"
        memory: "1.5Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    resources:
      requests:
        cpu: "200m"
        memory: "1Gi"
      limits:
        cpu: "500m"
        memory: "1.5Gi"
  gitaly:
    persistence:
      size: 50Gi
      storageClass: "local-path"
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
  postgresql:
    persistence:
      size: 10Gi
      storageClass: "local-path"
    resources:
      requests:
        cpu: "200m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
  redis:
    resources:
      requests:
        cpu: "100m"
        memory: "256Mi"
      limits:
        cpu: "200m"
        memory: "512Mi"
  gitlab-runner:
    install: false
  registry:
    enabled: false
  prometheus:
    install: false
  grafana:
    enabled: false
