apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/part-of: infrastructure
    app.kubernetes.io/component: authentication
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://github.com/clementpnn/infra.git"
    path: charts/keycloak
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: keycloak
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  info:
    - name: "Description"
      value: "Keycloak authentication and identity management production deployment"
    - name: "Owner"
      value: "contact@clementpnn.com"
    - name: "Documentation"
      value: "https://www.keycloak.org/documentation"
